before_install:
- npm install -g firebase-tools

before_script:
- firebase setup:emulators:firestore
- firebase serve --only firestore

language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: test
      node_js: "8"
      script: npm test && npm run coverage
