before_install:
- npm install -g firebase-tools

before_script:
- firebase setup:emulators:firestore
- firebase serve --host 127.0.0.1 --only firestore

language: node_js
node_js:
  - "8"

jobs:
  include:
    - stage: test
      node_js: "8"
      script: FIRESTORE_EMULATOR_HOST=[::1]:8080,127.0.0.1:8080 npm test && npm run coverage
